name: Deploy EchoNote to Cloud Run
on:
  push:
    branches: [main]

env:
  GCP_PROJECT: echonote-461723
  GCP_REGION: europe-west4
  SERVICE_NAME: echonote-api
  IMAGE_NAME: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image
        run: |
          IMAGE="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT/transcripts-repo/$IMAGE_NAME:$GITHUB_SHA"
          gcloud builds submit --tag $IMAGE .
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT/transcripts-repo/$IMAGE_NAME:$GITHUB_SHA" \
            --region $GCP_REGION \
            --platform managed \
            --allow-unauthenticated \
            --service-account transcripts-api-sa@$GCP_PROJECT.iam.gserviceaccount.com \
            --add-cloudsql-instances ${{ secrets.CLOUD_SQL_CONNECTION_NAME }} \
            --set-env-vars "GOOGLE_CLOUD_PROJECT=$GCP_PROJECT" \
            --set-env-vars "GOOGLE_CLOUD_LOCATION=$GCP_REGION" \
            --set-env-vars "GCS_BUCKET_NAME=$GCP_PROJECT-audio" \
            --set-secrets "JWT_SECRET_KEY=jwt-secret:latest" \
            --set-secrets "DATABASE_URL=database-url:latest" \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 10 \
            --timeout 900
      - name: Get Cloud Run URL
        run: |
          URL=$(gcloud run services describe $SERVICE_NAME --region=$GCP_REGION --format='value(status.url)')
          echo "🚀 Service deployed at: $URL"
          echo "📖 API docs available at: $URL/docs"
