name: Deploy to Cloud Run
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build & push image
        run: |
          IMAGE="europe-west4-docker.pkg.dev/$GCP_PROJECT/transcripts-repo/backend:$GITHUB_SHA"
          gcloud builds submit --tag $IMAGE .

      - name: Deploy Cloud Run
        run: |
          gcloud run deploy transcripts-api \
            --image $IMAGE \
            --region europe-west4 \
            --platform managed \
            --allow-unauthenticated=false \
            --set-env-vars "DB_INSTANCE=projects/$GCP_PROJECT/instances/transcripts-db" \
            --set-secrets "JWT_SECRET=projects/$GCP_PROJECT/secrets/jwt-secret:latest"
